#+title: Eruptions
#+startup: indent showall
* dev

** starting up

Created with `npx create-react-app eruptions`

In root directory start with `npm start`
App will load in `localhost:3000`

** css

*** TODO scss file
on archlinux with `sassc` (for compiling scss to css)

run `sassc index.scss index.css`

This is not dynamic ( while basic css is watched with `npm start`)
therefore need to find how to get emacs SASS mode to output css

** production (minify)

`npm run build`

** deployment

[[https://facebook.github.io/create-react-app/docs/deployment][The React Docs..]]

*** Deploy to Github

**** Step 1: Add homepage to package.json
 The step below is important!

 If you skip it, your app will not deploy correctly.

 Open your package.json and add a homepage field for your project:

   "homepage": "https://myusername.github.io/my-app",
 or for a GitHub user page:

   "homepage": "https://myusername.github.io",
 or for a custom domain page:

   "homepage": "https://mywebsite.com",
 Create React App uses the homepage field to determine the root URL in the built HTML file.

****  Step 2: Install gh-pages and add deploy to scripts in package.json
 Now, whenever you run npm run build, you will see a cheat sheet with instructions on how to deploy to GitHub Pages.

 To publish it at https://myusername.github.io/my-app, run:

 npm install --save gh-pages
 Alternatively you may use yarn:

 yarn add gh-pages
 Add the following scripts in your package.json:

   "scripts": {
 +   "predeploy": "npm run build",
 +   "deploy": "gh-pages -d build",
     "start": "react-scripts start",
     "build": "react-scripts build",
 The predeploy script will run automatically before deploy is run.

 If you are deploying to a GitHub user page instead of a project page you'll need to make one additional modification:

 Tweak your package.json scripts to push deployments to master:
   "scripts": {
     "predeploy": "npm run build",
 -   "deploy": "gh-pages -d build",
 +   "deploy": "gh-pages -b master -d build",

****  Step 3: Deploy the site by running npm run deploy
 Then run:

 `npm run deploy`


** DEVELOPMENT DOCUMENTATION FOR REFERENCE

